### PR TITLE
Fixes missing param for instance method signJWT

### PR DESCRIPTION
**Pull request by monkybrain**
Noticed that the instance method `signJWT` was missing the argument `payload` so went ahead and fixed it :-)

### CODE REVIEW

**Comment by oed** [comment]
Thanks for your contribution @monkybrain! 
It seems like you only edited the Readme, however this documentation is automatically generated by the jsdoc in the js files.
On another note. We are actually moving away from the muport library in favor for a 3id module that is in 3box-js. All functionality will still be there but with a slightly different api.

**Comment by monkybrain** [comment]
@oed I see! I edited the jsdocs instead now and ran the `build` and `generate-readme` scripts.

Ok, I'll look into 3id then :-)

**Comment by oed** [comment]
Thanks! 
It would be useful if you could maybe give us a short description of how you use muport so that we can make sure to document these things for 3id!

**Comment by oed** [comment]
Oh, seems like I forgot to merge this!

**Comment by oed** [comment]
Cool, yeah that makes sense! Need to think about how to expose that in the best possible way.

**Pull request merged**
